export type DataTableConfig = typeof dataTableConfig

export const dataTableConfig = {
  textOperators: [
    { label: "Contains", value: "ilike" as const },
    { label: "Does not contain", value: "not.ilike" as const },
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "neq" as const },
    { label: "Starts with", value: "like" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  numericOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "neq" as const },
    { label: "Is less than", value: "lt" as const },
    { label: "Is less than or equal to", value: "lte" as const },
    { label: "Is greater than", value: "gt" as const },
    { label: "Is greater than or equal to", value: "gte" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  dateOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "neq" as const },
    { label: "Is before", value: "lt" as const },
    { label: "Is after", value: "gt" as const },
    { label: "Is on or before", value: "lte" as const },
    { label: "Is on or after", value: "gte" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  selectOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "neq" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  multiSelectOperators: [
    { label: "Has any of", value: "in" as const },
    { label: "Has none of", value: "not.in" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  booleanOperators: [
    { label: "Is", value: "is" as const },
    { label: "Is not", value: "not.is" as const },
  ],
  uuidOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "neq" as const },
    { label: "Is empty", value: "is" as const },
    { label: "Is not empty", value: "not.is" as const },
  ],
  filterVariants: [
    "uuid",
    "text",
    "number",
    "range",
    "date",
    "time",
    "timetz",
    "timestamp",
    "timestamptz",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "eq",
    "neq",
    "lt",
    "lte",
    "gt",
    "gte",
    "like",
    "ilike",
    "is",
    "in",
    "contains",
    "overlaps",
    "not.ilike",
    "not.is",
    "not.in",
  ] as const,
}
