/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as SchemaChartIndexRouteImport } from "./routes/$schema/chart/index"
import { Route as SchemaDashboardIndexRouteImport } from "./routes/$schema/dashboard/index"
import { Route as SchemaIndexRouteImport } from "./routes/$schema/index"
import { Route as SchemaReportReportIndexRouteImport } from "./routes/$schema/report/$report/index"
import { Route as SchemaReportIndexRouteImport } from "./routes/$schema/report/index"
import { Route as SchemaResourceResourceResourceIdAuditRouteImport } from "./routes/$schema/resource/$resource/$resourceId/audit"
import { Route as SchemaResourceResourceResourceIdCommentRouteImport } from "./routes/$schema/resource/$resource/$resourceId/comment"
import { Route as SchemaResourceResourceResourceIdDetailRouteImport } from "./routes/$schema/resource/$resource/$resourceId/detail"
import { Route as SchemaResourceResourceResourceIdUpdateRouteImport } from "./routes/$schema/resource/$resource/$resourceId/update"
import { Route as SchemaResourceResourceCalendarCalendarIdRouteImport } from "./routes/$schema/resource/$resource/calendar/$calendarId"
import { Route as SchemaResourceResourceGalleryGalleryIdRouteImport } from "./routes/$schema/resource/$resource/gallery/$galleryId"
import { Route as SchemaResourceResourceGridRouteImport } from "./routes/$schema/resource/$resource/grid"
import { Route as SchemaResourceResourceIndexRouteImport } from "./routes/$schema/resource/$resource/index"
import { Route as SchemaResourceResourceKanbanKanbanIdRouteImport } from "./routes/$schema/resource/$resource/kanban/$kanbanId"
import { Route as SchemaResourceResourceListListIdRouteImport } from "./routes/$schema/resource/$resource/list/$listId"
import { Route as SchemaResourceResourceNewRouteImport } from "./routes/$schema/resource/$resource/new"
import { Route as SchemaResourceResourceRouteRouteImport } from "./routes/$schema/resource/$resource/route"
import { Route as SchemaResourceResourceSingleRouteImport } from "./routes/$schema/resource/$resource/single"
import { Route as SchemaResourceResourceTableRouteImport } from "./routes/$schema/resource/$resource/table"
import { Route as SchemaRouteRouteImport } from "./routes/$schema/route"
import { Route as SchemaSqlEditorSnippetIndexRouteImport } from "./routes/$schema/sql-editor/$snippet/index"
import { Route as SchemaTemplateTemplateIndexRouteImport } from "./routes/$schema/template/$template/index"
import { Route as SchemaTemplateIndexRouteImport } from "./routes/$schema/template/index"
import { Route as rootRouteImport } from "./routes/__root"
import { Route as AccountIdentitiesRouteImport } from "./routes/account/identities"
import { Route as AccountProfileRouteImport } from "./routes/account/profile"
import { Route as AccountRolesPermissionsRouteImport } from "./routes/account/roles-permissions"
import { Route as AccountRouteRouteImport } from "./routes/account/route"
import { Route as AccountSecurityRouteImport } from "./routes/account/security"
import { Route as AiChatIndexRouteImport } from "./routes/ai-chat/index"
import { Route as AiChatRouteRouteImport } from "./routes/ai-chat/route"
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password"
import { Route as AuthMfaRouteImport } from "./routes/auth/mfa"
import { Route as AuthRouteRouteImport } from "./routes/auth/route"
import { Route as AuthSignInRouteImport } from "./routes/auth/sign-in"
import { Route as AuthSignUpRouteImport } from "./routes/auth/sign-up"
import { Route as AuthUpdatePasswordRouteImport } from "./routes/auth/update-password"
import { Route as CoreAudit_logsAuditLogIdRouteImport } from "./routes/core/audit_logs/$auditLogId"
import { Route as CoreAudit_logsIndexRouteImport } from "./routes/core/audit_logs/index"
import { Route as CoreIndexRouteImport } from "./routes/core/index"
import { Route as CoreNotificationsIndexRouteImport } from "./routes/core/notifications/index"
import { Route as CoreRole_permissionsIndexRouteImport } from "./routes/core/role_permissions/index"
import { Route as CoreRole_permissionsNewRouteImport } from "./routes/core/role_permissions/new"
import { Route as CoreRouteRouteImport } from "./routes/core/route"
import { Route as CoreUser_rolesIndexRouteImport } from "./routes/core/user_roles/index"
import { Route as CoreUser_rolesNewRouteImport } from "./routes/core/user_roles/new"
import { Route as CoreUsersUserIdDangerRouteImport } from "./routes/core/users/$userId/danger"
import { Route as CoreUsersUserIdEditRouteImport } from "./routes/core/users/$userId/edit"
import { Route as CoreUsersUserIdIndexRouteImport } from "./routes/core/users/$userId/index"
import { Route as CoreUsersUserIdRouteRouteImport } from "./routes/core/users/$userId/route"
import { Route as CoreUsersUserIdSecurityRouteImport } from "./routes/core/users/$userId/security"
import { Route as CoreUsersIndexRouteImport } from "./routes/core/users/index"
import { Route as CoreUsersInviteRouteImport } from "./routes/core/users/invite"
import { Route as CoreUsersNewRouteImport } from "./routes/core/users/new"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as InitRouteImport } from "./routes/init"
import { Route as StorageBucketIdSplatRouteImport } from "./routes/storage/$bucketId/$"
import { Route as StorageBucketIdIndexRouteImport } from "./routes/storage/$bucketId/index"
import { Route as StorageBucketIdRouteRouteImport } from "./routes/storage/$bucketId/route"
import { Route as StorageIndexRouteImport } from "./routes/storage/index"
import { Route as StorageRouteRouteImport } from "./routes/storage/route"

const InitRoute = InitRouteImport.update({
  id: "/init",
  path: "/init",
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRouteRoute = StorageRouteRouteImport.update({
  id: "/storage",
  path: "/storage",
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRouteRoute = CoreRouteRouteImport.update({
  id: "/core",
  path: "/core",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRouteRoute = AiChatRouteRouteImport.update({
  id: "/ai-chat",
  path: "/ai-chat",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRouteRoute = SchemaRouteRouteImport.update({
  id: "/$schema",
  path: "/$schema",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => StorageRouteRoute,
} as any)
const CoreIndexRoute = CoreIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CoreRouteRoute,
} as any)
const AiChatIndexRoute = AiChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AiChatRouteRoute,
} as any)
const SchemaIndexRoute = SchemaIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: "/update-password",
  path: "/update-password",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: "/mfa",
  path: "/mfa",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: "/security",
  path: "/security",
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRolesPermissionsRoute = AccountRolesPermissionsRouteImport.update({
  id: "/roles-permissions",
  path: "/roles-permissions",
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountIdentitiesRoute = AccountIdentitiesRouteImport.update({
  id: "/identities",
  path: "/identities",
  getParentRoute: () => AccountRouteRoute,
} as any)
const StorageBucketIdRouteRoute = StorageBucketIdRouteRouteImport.update({
  id: "/$bucketId",
  path: "/$bucketId",
  getParentRoute: () => StorageRouteRoute,
} as any)
const StorageBucketIdIndexRoute = StorageBucketIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => StorageBucketIdRouteRoute,
} as any)
const CoreUsersIndexRoute = CoreUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUser_rolesIndexRoute = CoreUser_rolesIndexRouteImport.update({
  id: "/user_roles/",
  path: "/user_roles/",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRole_permissionsIndexRoute =
  CoreRole_permissionsIndexRouteImport.update({
    id: "/role_permissions/",
    path: "/role_permissions/",
    getParentRoute: () => CoreRouteRoute,
  } as any)
const CoreNotificationsIndexRoute = CoreNotificationsIndexRouteImport.update({
  id: "/notifications/",
  path: "/notifications/",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreAudit_logsIndexRoute = CoreAudit_logsIndexRouteImport.update({
  id: "/audit_logs/",
  path: "/audit_logs/",
  getParentRoute: () => CoreRouteRoute,
} as any)
const SchemaTemplateIndexRoute = SchemaTemplateIndexRouteImport.update({
  id: "/template/",
  path: "/template/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaReportIndexRoute = SchemaReportIndexRouteImport.update({
  id: "/report/",
  path: "/report/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaDashboardIndexRoute = SchemaDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaChartIndexRoute = SchemaChartIndexRouteImport.update({
  id: "/chart/",
  path: "/chart/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const StorageBucketIdSplatRoute = StorageBucketIdSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => StorageBucketIdRouteRoute,
} as any)
const CoreUsersNewRoute = CoreUsersNewRouteImport.update({
  id: "/users/new",
  path: "/users/new",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUsersInviteRoute = CoreUsersInviteRouteImport.update({
  id: "/users/invite",
  path: "/users/invite",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUser_rolesNewRoute = CoreUser_rolesNewRouteImport.update({
  id: "/user_roles/new",
  path: "/user_roles/new",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreRole_permissionsNewRoute = CoreRole_permissionsNewRouteImport.update({
  id: "/role_permissions/new",
  path: "/role_permissions/new",
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreAudit_logsAuditLogIdRoute =
  CoreAudit_logsAuditLogIdRouteImport.update({
    id: "/audit_logs/$auditLogId",
    path: "/audit_logs/$auditLogId",
    getParentRoute: () => CoreRouteRoute,
  } as any)
const CoreUsersUserIdRouteRoute = CoreUsersUserIdRouteRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => CoreRouteRoute,
} as any)
const SchemaResourceResourceRouteRoute =
  SchemaResourceResourceRouteRouteImport.update({
    id: "/resource/$resource",
    path: "/resource/$resource",
    getParentRoute: () => SchemaRouteRoute,
  } as any)
const CoreUsersUserIdIndexRoute = CoreUsersUserIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const SchemaTemplateTemplateIndexRoute =
  SchemaTemplateTemplateIndexRouteImport.update({
    id: "/template/$template/",
    path: "/template/$template/",
    getParentRoute: () => SchemaRouteRoute,
  } as any)
const SchemaSqlEditorSnippetIndexRoute =
  SchemaSqlEditorSnippetIndexRouteImport.update({
    id: "/sql-editor/$snippet/",
    path: "/sql-editor/$snippet/",
    getParentRoute: () => SchemaRouteRoute,
  } as any)
const SchemaResourceResourceIndexRoute =
  SchemaResourceResourceIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaReportReportIndexRoute = SchemaReportReportIndexRouteImport.update({
  id: "/report/$report/",
  path: "/report/$report/",
  getParentRoute: () => SchemaRouteRoute,
} as any)
const CoreUsersUserIdSecurityRoute = CoreUsersUserIdSecurityRouteImport.update({
  id: "/security",
  path: "/security",
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const CoreUsersUserIdEditRoute = CoreUsersUserIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const CoreUsersUserIdDangerRoute = CoreUsersUserIdDangerRouteImport.update({
  id: "/danger",
  path: "/danger",
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const SchemaResourceResourceTableRoute =
  SchemaResourceResourceTableRouteImport.update({
    id: "/table",
    path: "/table",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceSingleRoute =
  SchemaResourceResourceSingleRouteImport.update({
    id: "/single",
    path: "/single",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceNewRoute =
  SchemaResourceResourceNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceGridRoute =
  SchemaResourceResourceGridRouteImport.update({
    id: "/grid",
    path: "/grid",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceListListIdRoute =
  SchemaResourceResourceListListIdRouteImport.update({
    id: "/list/$listId",
    path: "/list/$listId",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceKanbanKanbanIdRoute =
  SchemaResourceResourceKanbanKanbanIdRouteImport.update({
    id: "/kanban/$kanbanId",
    path: "/kanban/$kanbanId",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceGalleryGalleryIdRoute =
  SchemaResourceResourceGalleryGalleryIdRouteImport.update({
    id: "/gallery/$galleryId",
    path: "/gallery/$galleryId",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceCalendarCalendarIdRoute =
  SchemaResourceResourceCalendarCalendarIdRouteImport.update({
    id: "/calendar/$calendarId",
    path: "/calendar/$calendarId",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdUpdateRoute =
  SchemaResourceResourceResourceIdUpdateRouteImport.update({
    id: "/$resourceId/update",
    path: "/$resourceId/update",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailRoute =
  SchemaResourceResourceResourceIdDetailRouteImport.update({
    id: "/$resourceId/detail",
    path: "/$resourceId/detail",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdCommentRoute =
  SchemaResourceResourceResourceIdCommentRouteImport.update({
    id: "/$resourceId/comment",
    path: "/$resourceId/comment",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdAuditRoute =
  SchemaResourceResourceResourceIdAuditRouteImport.update({
    id: "/$resourceId/audit",
    path: "/$resourceId/audit",
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$schema": typeof SchemaRouteRouteWithChildren
  "/account": typeof AccountRouteRouteWithChildren
  "/ai-chat": typeof AiChatRouteRouteWithChildren
  "/auth": typeof AuthRouteRouteWithChildren
  "/core": typeof CoreRouteRouteWithChildren
  "/storage": typeof StorageRouteRouteWithChildren
  "/init": typeof InitRoute
  "/storage/$bucketId": typeof StorageBucketIdRouteRouteWithChildren
  "/account/identities": typeof AccountIdentitiesRoute
  "/account/profile": typeof AccountProfileRoute
  "/account/roles-permissions": typeof AccountRolesPermissionsRoute
  "/account/security": typeof AccountSecurityRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/mfa": typeof AuthMfaRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/auth/update-password": typeof AuthUpdatePasswordRoute
  "/$schema/": typeof SchemaIndexRoute
  "/ai-chat/": typeof AiChatIndexRoute
  "/core/": typeof CoreIndexRoute
  "/storage/": typeof StorageIndexRoute
  "/$schema/resource/$resource": typeof SchemaResourceResourceRouteRouteWithChildren
  "/core/users/$userId": typeof CoreUsersUserIdRouteRouteWithChildren
  "/core/audit_logs/$auditLogId": typeof CoreAudit_logsAuditLogIdRoute
  "/core/role_permissions/new": typeof CoreRole_permissionsNewRoute
  "/core/user_roles/new": typeof CoreUser_rolesNewRoute
  "/core/users/invite": typeof CoreUsersInviteRoute
  "/core/users/new": typeof CoreUsersNewRoute
  "/storage/$bucketId/$": typeof StorageBucketIdSplatRoute
  "/$schema/chart/": typeof SchemaChartIndexRoute
  "/$schema/dashboard/": typeof SchemaDashboardIndexRoute
  "/$schema/report/": typeof SchemaReportIndexRoute
  "/$schema/template/": typeof SchemaTemplateIndexRoute
  "/core/audit_logs/": typeof CoreAudit_logsIndexRoute
  "/core/notifications/": typeof CoreNotificationsIndexRoute
  "/core/role_permissions/": typeof CoreRole_permissionsIndexRoute
  "/core/user_roles/": typeof CoreUser_rolesIndexRoute
  "/core/users/": typeof CoreUsersIndexRoute
  "/storage/$bucketId/": typeof StorageBucketIdIndexRoute
  "/$schema/resource/$resource/grid": typeof SchemaResourceResourceGridRoute
  "/$schema/resource/$resource/new": typeof SchemaResourceResourceNewRoute
  "/$schema/resource/$resource/single": typeof SchemaResourceResourceSingleRoute
  "/$schema/resource/$resource/table": typeof SchemaResourceResourceTableRoute
  "/core/users/$userId/danger": typeof CoreUsersUserIdDangerRoute
  "/core/users/$userId/edit": typeof CoreUsersUserIdEditRoute
  "/core/users/$userId/security": typeof CoreUsersUserIdSecurityRoute
  "/$schema/report/$report/": typeof SchemaReportReportIndexRoute
  "/$schema/resource/$resource/": typeof SchemaResourceResourceIndexRoute
  "/$schema/sql-editor/$snippet/": typeof SchemaSqlEditorSnippetIndexRoute
  "/$schema/template/$template/": typeof SchemaTemplateTemplateIndexRoute
  "/core/users/$userId/": typeof CoreUsersUserIdIndexRoute
  "/$schema/resource/$resource/$resourceId/audit": typeof SchemaResourceResourceResourceIdAuditRoute
  "/$schema/resource/$resource/$resourceId/comment": typeof SchemaResourceResourceResourceIdCommentRoute
  "/$schema/resource/$resource/$resourceId/detail": typeof SchemaResourceResourceResourceIdDetailRoute
  "/$schema/resource/$resource/$resourceId/update": typeof SchemaResourceResourceResourceIdUpdateRoute
  "/$schema/resource/$resource/calendar/$calendarId": typeof SchemaResourceResourceCalendarCalendarIdRoute
  "/$schema/resource/$resource/gallery/$galleryId": typeof SchemaResourceResourceGalleryGalleryIdRoute
  "/$schema/resource/$resource/kanban/$kanbanId": typeof SchemaResourceResourceKanbanKanbanIdRoute
  "/$schema/resource/$resource/list/$listId": typeof SchemaResourceResourceListListIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/account": typeof AccountRouteRouteWithChildren
  "/auth": typeof AuthRouteRouteWithChildren
  "/init": typeof InitRoute
  "/account/identities": typeof AccountIdentitiesRoute
  "/account/profile": typeof AccountProfileRoute
  "/account/roles-permissions": typeof AccountRolesPermissionsRoute
  "/account/security": typeof AccountSecurityRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/mfa": typeof AuthMfaRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/auth/update-password": typeof AuthUpdatePasswordRoute
  "/$schema": typeof SchemaIndexRoute
  "/ai-chat": typeof AiChatIndexRoute
  "/core": typeof CoreIndexRoute
  "/storage": typeof StorageIndexRoute
  "/core/audit_logs/$auditLogId": typeof CoreAudit_logsAuditLogIdRoute
  "/core/role_permissions/new": typeof CoreRole_permissionsNewRoute
  "/core/user_roles/new": typeof CoreUser_rolesNewRoute
  "/core/users/invite": typeof CoreUsersInviteRoute
  "/core/users/new": typeof CoreUsersNewRoute
  "/storage/$bucketId/$": typeof StorageBucketIdSplatRoute
  "/$schema/chart": typeof SchemaChartIndexRoute
  "/$schema/dashboard": typeof SchemaDashboardIndexRoute
  "/$schema/report": typeof SchemaReportIndexRoute
  "/$schema/template": typeof SchemaTemplateIndexRoute
  "/core/audit_logs": typeof CoreAudit_logsIndexRoute
  "/core/notifications": typeof CoreNotificationsIndexRoute
  "/core/role_permissions": typeof CoreRole_permissionsIndexRoute
  "/core/user_roles": typeof CoreUser_rolesIndexRoute
  "/core/users": typeof CoreUsersIndexRoute
  "/storage/$bucketId": typeof StorageBucketIdIndexRoute
  "/$schema/resource/$resource/grid": typeof SchemaResourceResourceGridRoute
  "/$schema/resource/$resource/new": typeof SchemaResourceResourceNewRoute
  "/$schema/resource/$resource/single": typeof SchemaResourceResourceSingleRoute
  "/$schema/resource/$resource/table": typeof SchemaResourceResourceTableRoute
  "/core/users/$userId/danger": typeof CoreUsersUserIdDangerRoute
  "/core/users/$userId/edit": typeof CoreUsersUserIdEditRoute
  "/core/users/$userId/security": typeof CoreUsersUserIdSecurityRoute
  "/$schema/report/$report": typeof SchemaReportReportIndexRoute
  "/$schema/resource/$resource": typeof SchemaResourceResourceIndexRoute
  "/$schema/sql-editor/$snippet": typeof SchemaSqlEditorSnippetIndexRoute
  "/$schema/template/$template": typeof SchemaTemplateTemplateIndexRoute
  "/core/users/$userId": typeof CoreUsersUserIdIndexRoute
  "/$schema/resource/$resource/$resourceId/audit": typeof SchemaResourceResourceResourceIdAuditRoute
  "/$schema/resource/$resource/$resourceId/comment": typeof SchemaResourceResourceResourceIdCommentRoute
  "/$schema/resource/$resource/$resourceId/detail": typeof SchemaResourceResourceResourceIdDetailRoute
  "/$schema/resource/$resource/$resourceId/update": typeof SchemaResourceResourceResourceIdUpdateRoute
  "/$schema/resource/$resource/calendar/$calendarId": typeof SchemaResourceResourceCalendarCalendarIdRoute
  "/$schema/resource/$resource/gallery/$galleryId": typeof SchemaResourceResourceGalleryGalleryIdRoute
  "/$schema/resource/$resource/kanban/$kanbanId": typeof SchemaResourceResourceKanbanKanbanIdRoute
  "/$schema/resource/$resource/list/$listId": typeof SchemaResourceResourceListListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$schema": typeof SchemaRouteRouteWithChildren
  "/account": typeof AccountRouteRouteWithChildren
  "/ai-chat": typeof AiChatRouteRouteWithChildren
  "/auth": typeof AuthRouteRouteWithChildren
  "/core": typeof CoreRouteRouteWithChildren
  "/storage": typeof StorageRouteRouteWithChildren
  "/init": typeof InitRoute
  "/storage/$bucketId": typeof StorageBucketIdRouteRouteWithChildren
  "/account/identities": typeof AccountIdentitiesRoute
  "/account/profile": typeof AccountProfileRoute
  "/account/roles-permissions": typeof AccountRolesPermissionsRoute
  "/account/security": typeof AccountSecurityRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/mfa": typeof AuthMfaRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/auth/update-password": typeof AuthUpdatePasswordRoute
  "/$schema/": typeof SchemaIndexRoute
  "/ai-chat/": typeof AiChatIndexRoute
  "/core/": typeof CoreIndexRoute
  "/storage/": typeof StorageIndexRoute
  "/$schema/resource/$resource": typeof SchemaResourceResourceRouteRouteWithChildren
  "/core/users/$userId": typeof CoreUsersUserIdRouteRouteWithChildren
  "/core/audit_logs/$auditLogId": typeof CoreAudit_logsAuditLogIdRoute
  "/core/role_permissions/new": typeof CoreRole_permissionsNewRoute
  "/core/user_roles/new": typeof CoreUser_rolesNewRoute
  "/core/users/invite": typeof CoreUsersInviteRoute
  "/core/users/new": typeof CoreUsersNewRoute
  "/storage/$bucketId/$": typeof StorageBucketIdSplatRoute
  "/$schema/chart/": typeof SchemaChartIndexRoute
  "/$schema/dashboard/": typeof SchemaDashboardIndexRoute
  "/$schema/report/": typeof SchemaReportIndexRoute
  "/$schema/template/": typeof SchemaTemplateIndexRoute
  "/core/audit_logs/": typeof CoreAudit_logsIndexRoute
  "/core/notifications/": typeof CoreNotificationsIndexRoute
  "/core/role_permissions/": typeof CoreRole_permissionsIndexRoute
  "/core/user_roles/": typeof CoreUser_rolesIndexRoute
  "/core/users/": typeof CoreUsersIndexRoute
  "/storage/$bucketId/": typeof StorageBucketIdIndexRoute
  "/$schema/resource/$resource/grid": typeof SchemaResourceResourceGridRoute
  "/$schema/resource/$resource/new": typeof SchemaResourceResourceNewRoute
  "/$schema/resource/$resource/single": typeof SchemaResourceResourceSingleRoute
  "/$schema/resource/$resource/table": typeof SchemaResourceResourceTableRoute
  "/core/users/$userId/danger": typeof CoreUsersUserIdDangerRoute
  "/core/users/$userId/edit": typeof CoreUsersUserIdEditRoute
  "/core/users/$userId/security": typeof CoreUsersUserIdSecurityRoute
  "/$schema/report/$report/": typeof SchemaReportReportIndexRoute
  "/$schema/resource/$resource/": typeof SchemaResourceResourceIndexRoute
  "/$schema/sql-editor/$snippet/": typeof SchemaSqlEditorSnippetIndexRoute
  "/$schema/template/$template/": typeof SchemaTemplateTemplateIndexRoute
  "/core/users/$userId/": typeof CoreUsersUserIdIndexRoute
  "/$schema/resource/$resource/$resourceId/audit": typeof SchemaResourceResourceResourceIdAuditRoute
  "/$schema/resource/$resource/$resourceId/comment": typeof SchemaResourceResourceResourceIdCommentRoute
  "/$schema/resource/$resource/$resourceId/detail": typeof SchemaResourceResourceResourceIdDetailRoute
  "/$schema/resource/$resource/$resourceId/update": typeof SchemaResourceResourceResourceIdUpdateRoute
  "/$schema/resource/$resource/calendar/$calendarId": typeof SchemaResourceResourceCalendarCalendarIdRoute
  "/$schema/resource/$resource/gallery/$galleryId": typeof SchemaResourceResourceGalleryGalleryIdRoute
  "/$schema/resource/$resource/kanban/$kanbanId": typeof SchemaResourceResourceKanbanKanbanIdRoute
  "/$schema/resource/$resource/list/$listId": typeof SchemaResourceResourceListListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$schema"
    | "/account"
    | "/ai-chat"
    | "/auth"
    | "/core"
    | "/storage"
    | "/init"
    | "/storage/$bucketId"
    | "/account/identities"
    | "/account/profile"
    | "/account/roles-permissions"
    | "/account/security"
    | "/auth/forgot-password"
    | "/auth/mfa"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/update-password"
    | "/$schema/"
    | "/ai-chat/"
    | "/core/"
    | "/storage/"
    | "/$schema/resource/$resource"
    | "/core/users/$userId"
    | "/core/audit_logs/$auditLogId"
    | "/core/role_permissions/new"
    | "/core/user_roles/new"
    | "/core/users/invite"
    | "/core/users/new"
    | "/storage/$bucketId/$"
    | "/$schema/chart/"
    | "/$schema/dashboard/"
    | "/$schema/report/"
    | "/$schema/template/"
    | "/core/audit_logs/"
    | "/core/notifications/"
    | "/core/role_permissions/"
    | "/core/user_roles/"
    | "/core/users/"
    | "/storage/$bucketId/"
    | "/$schema/resource/$resource/grid"
    | "/$schema/resource/$resource/new"
    | "/$schema/resource/$resource/single"
    | "/$schema/resource/$resource/table"
    | "/core/users/$userId/danger"
    | "/core/users/$userId/edit"
    | "/core/users/$userId/security"
    | "/$schema/report/$report/"
    | "/$schema/resource/$resource/"
    | "/$schema/sql-editor/$snippet/"
    | "/$schema/template/$template/"
    | "/core/users/$userId/"
    | "/$schema/resource/$resource/$resourceId/audit"
    | "/$schema/resource/$resource/$resourceId/comment"
    | "/$schema/resource/$resource/$resourceId/detail"
    | "/$schema/resource/$resource/$resourceId/update"
    | "/$schema/resource/$resource/calendar/$calendarId"
    | "/$schema/resource/$resource/gallery/$galleryId"
    | "/$schema/resource/$resource/kanban/$kanbanId"
    | "/$schema/resource/$resource/list/$listId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/account"
    | "/auth"
    | "/init"
    | "/account/identities"
    | "/account/profile"
    | "/account/roles-permissions"
    | "/account/security"
    | "/auth/forgot-password"
    | "/auth/mfa"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/update-password"
    | "/$schema"
    | "/ai-chat"
    | "/core"
    | "/storage"
    | "/core/audit_logs/$auditLogId"
    | "/core/role_permissions/new"
    | "/core/user_roles/new"
    | "/core/users/invite"
    | "/core/users/new"
    | "/storage/$bucketId/$"
    | "/$schema/chart"
    | "/$schema/dashboard"
    | "/$schema/report"
    | "/$schema/template"
    | "/core/audit_logs"
    | "/core/notifications"
    | "/core/role_permissions"
    | "/core/user_roles"
    | "/core/users"
    | "/storage/$bucketId"
    | "/$schema/resource/$resource/grid"
    | "/$schema/resource/$resource/new"
    | "/$schema/resource/$resource/single"
    | "/$schema/resource/$resource/table"
    | "/core/users/$userId/danger"
    | "/core/users/$userId/edit"
    | "/core/users/$userId/security"
    | "/$schema/report/$report"
    | "/$schema/resource/$resource"
    | "/$schema/sql-editor/$snippet"
    | "/$schema/template/$template"
    | "/core/users/$userId"
    | "/$schema/resource/$resource/$resourceId/audit"
    | "/$schema/resource/$resource/$resourceId/comment"
    | "/$schema/resource/$resource/$resourceId/detail"
    | "/$schema/resource/$resource/$resourceId/update"
    | "/$schema/resource/$resource/calendar/$calendarId"
    | "/$schema/resource/$resource/gallery/$galleryId"
    | "/$schema/resource/$resource/kanban/$kanbanId"
    | "/$schema/resource/$resource/list/$listId"
  id:
    | "__root__"
    | "/"
    | "/$schema"
    | "/account"
    | "/ai-chat"
    | "/auth"
    | "/core"
    | "/storage"
    | "/init"
    | "/storage/$bucketId"
    | "/account/identities"
    | "/account/profile"
    | "/account/roles-permissions"
    | "/account/security"
    | "/auth/forgot-password"
    | "/auth/mfa"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/update-password"
    | "/$schema/"
    | "/ai-chat/"
    | "/core/"
    | "/storage/"
    | "/$schema/resource/$resource"
    | "/core/users/$userId"
    | "/core/audit_logs/$auditLogId"
    | "/core/role_permissions/new"
    | "/core/user_roles/new"
    | "/core/users/invite"
    | "/core/users/new"
    | "/storage/$bucketId/$"
    | "/$schema/chart/"
    | "/$schema/dashboard/"
    | "/$schema/report/"
    | "/$schema/template/"
    | "/core/audit_logs/"
    | "/core/notifications/"
    | "/core/role_permissions/"
    | "/core/user_roles/"
    | "/core/users/"
    | "/storage/$bucketId/"
    | "/$schema/resource/$resource/grid"
    | "/$schema/resource/$resource/new"
    | "/$schema/resource/$resource/single"
    | "/$schema/resource/$resource/table"
    | "/core/users/$userId/danger"
    | "/core/users/$userId/edit"
    | "/core/users/$userId/security"
    | "/$schema/report/$report/"
    | "/$schema/resource/$resource/"
    | "/$schema/sql-editor/$snippet/"
    | "/$schema/template/$template/"
    | "/core/users/$userId/"
    | "/$schema/resource/$resource/$resourceId/audit"
    | "/$schema/resource/$resource/$resourceId/comment"
    | "/$schema/resource/$resource/$resourceId/detail"
    | "/$schema/resource/$resource/$resourceId/update"
    | "/$schema/resource/$resource/calendar/$calendarId"
    | "/$schema/resource/$resource/gallery/$galleryId"
    | "/$schema/resource/$resource/kanban/$kanbanId"
    | "/$schema/resource/$resource/list/$listId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemaRouteRoute: typeof SchemaRouteRouteWithChildren
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AiChatRouteRoute: typeof AiChatRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CoreRouteRoute: typeof CoreRouteRouteWithChildren
  StorageRouteRoute: typeof StorageRouteRouteWithChildren
  InitRoute: typeof InitRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/init": {
      id: "/init"
      path: "/init"
      fullPath: "/init"
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/storage": {
      id: "/storage"
      path: "/storage"
      fullPath: "/storage"
      preLoaderRoute: typeof StorageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/core": {
      id: "/core"
      path: "/core"
      fullPath: "/core"
      preLoaderRoute: typeof CoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ai-chat": {
      id: "/ai-chat"
      path: "/ai-chat"
      fullPath: "/ai-chat"
      preLoaderRoute: typeof AiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account": {
      id: "/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$schema": {
      id: "/$schema"
      path: "/$schema"
      fullPath: "/$schema"
      preLoaderRoute: typeof SchemaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/storage/": {
      id: "/storage/"
      path: "/"
      fullPath: "/storage/"
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof StorageRouteRoute
    }
    "/core/": {
      id: "/core/"
      path: "/"
      fullPath: "/core/"
      preLoaderRoute: typeof CoreIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/ai-chat/": {
      id: "/ai-chat/"
      path: "/"
      fullPath: "/ai-chat/"
      preLoaderRoute: typeof AiChatIndexRouteImport
      parentRoute: typeof AiChatRouteRoute
    }
    "/$schema/": {
      id: "/$schema/"
      path: "/"
      fullPath: "/$schema/"
      preLoaderRoute: typeof SchemaIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/auth/update-password": {
      id: "/auth/update-password"
      path: "/update-password"
      fullPath: "/auth/update-password"
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/sign-up": {
      id: "/auth/sign-up"
      path: "/sign-up"
      fullPath: "/auth/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/sign-in": {
      id: "/auth/sign-in"
      path: "/sign-in"
      fullPath: "/auth/sign-in"
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/mfa": {
      id: "/auth/mfa"
      path: "/mfa"
      fullPath: "/auth/mfa"
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/account/security": {
      id: "/account/security"
      path: "/security"
      fullPath: "/account/security"
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    "/account/roles-permissions": {
      id: "/account/roles-permissions"
      path: "/roles-permissions"
      fullPath: "/account/roles-permissions"
      preLoaderRoute: typeof AccountRolesPermissionsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    "/account/profile": {
      id: "/account/profile"
      path: "/profile"
      fullPath: "/account/profile"
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    "/account/identities": {
      id: "/account/identities"
      path: "/identities"
      fullPath: "/account/identities"
      preLoaderRoute: typeof AccountIdentitiesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    "/storage/$bucketId": {
      id: "/storage/$bucketId"
      path: "/$bucketId"
      fullPath: "/storage/$bucketId"
      preLoaderRoute: typeof StorageBucketIdRouteRouteImport
      parentRoute: typeof StorageRouteRoute
    }
    "/storage/$bucketId/": {
      id: "/storage/$bucketId/"
      path: "/"
      fullPath: "/storage/$bucketId/"
      preLoaderRoute: typeof StorageBucketIdIndexRouteImport
      parentRoute: typeof StorageBucketIdRouteRoute
    }
    "/core/users/": {
      id: "/core/users/"
      path: "/users"
      fullPath: "/core/users/"
      preLoaderRoute: typeof CoreUsersIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/user_roles/": {
      id: "/core/user_roles/"
      path: "/user_roles"
      fullPath: "/core/user_roles/"
      preLoaderRoute: typeof CoreUser_rolesIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/role_permissions/": {
      id: "/core/role_permissions/"
      path: "/role_permissions"
      fullPath: "/core/role_permissions/"
      preLoaderRoute: typeof CoreRole_permissionsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/notifications/": {
      id: "/core/notifications/"
      path: "/notifications"
      fullPath: "/core/notifications/"
      preLoaderRoute: typeof CoreNotificationsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/audit_logs/": {
      id: "/core/audit_logs/"
      path: "/audit_logs"
      fullPath: "/core/audit_logs/"
      preLoaderRoute: typeof CoreAudit_logsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/$schema/template/": {
      id: "/$schema/template/"
      path: "/template"
      fullPath: "/$schema/template/"
      preLoaderRoute: typeof SchemaTemplateIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/$schema/report/": {
      id: "/$schema/report/"
      path: "/report"
      fullPath: "/$schema/report/"
      preLoaderRoute: typeof SchemaReportIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/$schema/dashboard/": {
      id: "/$schema/dashboard/"
      path: "/dashboard"
      fullPath: "/$schema/dashboard/"
      preLoaderRoute: typeof SchemaDashboardIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/$schema/chart/": {
      id: "/$schema/chart/"
      path: "/chart"
      fullPath: "/$schema/chart/"
      preLoaderRoute: typeof SchemaChartIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/storage/$bucketId/$": {
      id: "/storage/$bucketId/$"
      path: "/$"
      fullPath: "/storage/$bucketId/$"
      preLoaderRoute: typeof StorageBucketIdSplatRouteImport
      parentRoute: typeof StorageBucketIdRouteRoute
    }
    "/core/users/new": {
      id: "/core/users/new"
      path: "/users/new"
      fullPath: "/core/users/new"
      preLoaderRoute: typeof CoreUsersNewRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/users/invite": {
      id: "/core/users/invite"
      path: "/users/invite"
      fullPath: "/core/users/invite"
      preLoaderRoute: typeof CoreUsersInviteRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/user_roles/new": {
      id: "/core/user_roles/new"
      path: "/user_roles/new"
      fullPath: "/core/user_roles/new"
      preLoaderRoute: typeof CoreUser_rolesNewRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/role_permissions/new": {
      id: "/core/role_permissions/new"
      path: "/role_permissions/new"
      fullPath: "/core/role_permissions/new"
      preLoaderRoute: typeof CoreRole_permissionsNewRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/audit_logs/$auditLogId": {
      id: "/core/audit_logs/$auditLogId"
      path: "/audit_logs/$auditLogId"
      fullPath: "/core/audit_logs/$auditLogId"
      preLoaderRoute: typeof CoreAudit_logsAuditLogIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/core/users/$userId": {
      id: "/core/users/$userId"
      path: "/users/$userId"
      fullPath: "/core/users/$userId"
      preLoaderRoute: typeof CoreUsersUserIdRouteRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    "/$schema/resource/$resource": {
      id: "/$schema/resource/$resource"
      path: "/resource/$resource"
      fullPath: "/$schema/resource/$resource"
      preLoaderRoute: typeof SchemaResourceResourceRouteRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/core/users/$userId/": {
      id: "/core/users/$userId/"
      path: "/"
      fullPath: "/core/users/$userId/"
      preLoaderRoute: typeof CoreUsersUserIdIndexRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    "/$schema/template/$template/": {
      id: "/$schema/template/$template/"
      path: "/template/$template"
      fullPath: "/$schema/template/$template/"
      preLoaderRoute: typeof SchemaTemplateTemplateIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/$schema/sql-editor/$snippet/": {
      id: "/$schema/sql-editor/$snippet/"
      path: "/sql-editor/$snippet"
      fullPath: "/$schema/sql-editor/$snippet/"
      preLoaderRoute: typeof SchemaSqlEditorSnippetIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/$schema/resource/$resource/": {
      id: "/$schema/resource/$resource/"
      path: "/"
      fullPath: "/$schema/resource/$resource/"
      preLoaderRoute: typeof SchemaResourceResourceIndexRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/report/$report/": {
      id: "/$schema/report/$report/"
      path: "/report/$report"
      fullPath: "/$schema/report/$report/"
      preLoaderRoute: typeof SchemaReportReportIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    "/core/users/$userId/security": {
      id: "/core/users/$userId/security"
      path: "/security"
      fullPath: "/core/users/$userId/security"
      preLoaderRoute: typeof CoreUsersUserIdSecurityRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    "/core/users/$userId/edit": {
      id: "/core/users/$userId/edit"
      path: "/edit"
      fullPath: "/core/users/$userId/edit"
      preLoaderRoute: typeof CoreUsersUserIdEditRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    "/core/users/$userId/danger": {
      id: "/core/users/$userId/danger"
      path: "/danger"
      fullPath: "/core/users/$userId/danger"
      preLoaderRoute: typeof CoreUsersUserIdDangerRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    "/$schema/resource/$resource/table": {
      id: "/$schema/resource/$resource/table"
      path: "/table"
      fullPath: "/$schema/resource/$resource/table"
      preLoaderRoute: typeof SchemaResourceResourceTableRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/single": {
      id: "/$schema/resource/$resource/single"
      path: "/single"
      fullPath: "/$schema/resource/$resource/single"
      preLoaderRoute: typeof SchemaResourceResourceSingleRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/new": {
      id: "/$schema/resource/$resource/new"
      path: "/new"
      fullPath: "/$schema/resource/$resource/new"
      preLoaderRoute: typeof SchemaResourceResourceNewRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/grid": {
      id: "/$schema/resource/$resource/grid"
      path: "/grid"
      fullPath: "/$schema/resource/$resource/grid"
      preLoaderRoute: typeof SchemaResourceResourceGridRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/list/$listId": {
      id: "/$schema/resource/$resource/list/$listId"
      path: "/list/$listId"
      fullPath: "/$schema/resource/$resource/list/$listId"
      preLoaderRoute: typeof SchemaResourceResourceListListIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/kanban/$kanbanId": {
      id: "/$schema/resource/$resource/kanban/$kanbanId"
      path: "/kanban/$kanbanId"
      fullPath: "/$schema/resource/$resource/kanban/$kanbanId"
      preLoaderRoute: typeof SchemaResourceResourceKanbanKanbanIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/gallery/$galleryId": {
      id: "/$schema/resource/$resource/gallery/$galleryId"
      path: "/gallery/$galleryId"
      fullPath: "/$schema/resource/$resource/gallery/$galleryId"
      preLoaderRoute: typeof SchemaResourceResourceGalleryGalleryIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/calendar/$calendarId": {
      id: "/$schema/resource/$resource/calendar/$calendarId"
      path: "/calendar/$calendarId"
      fullPath: "/$schema/resource/$resource/calendar/$calendarId"
      preLoaderRoute: typeof SchemaResourceResourceCalendarCalendarIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/$resourceId/update": {
      id: "/$schema/resource/$resource/$resourceId/update"
      path: "/$resourceId/update"
      fullPath: "/$schema/resource/$resource/$resourceId/update"
      preLoaderRoute: typeof SchemaResourceResourceResourceIdUpdateRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/$resourceId/detail": {
      id: "/$schema/resource/$resource/$resourceId/detail"
      path: "/$resourceId/detail"
      fullPath: "/$schema/resource/$resource/$resourceId/detail"
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/$resourceId/comment": {
      id: "/$schema/resource/$resource/$resourceId/comment"
      path: "/$resourceId/comment"
      fullPath: "/$schema/resource/$resource/$resourceId/comment"
      preLoaderRoute: typeof SchemaResourceResourceResourceIdCommentRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    "/$schema/resource/$resource/$resourceId/audit": {
      id: "/$schema/resource/$resource/$resourceId/audit"
      path: "/$resourceId/audit"
      fullPath: "/$schema/resource/$resource/$resourceId/audit"
      preLoaderRoute: typeof SchemaResourceResourceResourceIdAuditRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
  }
}

interface SchemaResourceResourceRouteRouteChildren {
  SchemaResourceResourceGridRoute: typeof SchemaResourceResourceGridRoute
  SchemaResourceResourceNewRoute: typeof SchemaResourceResourceNewRoute
  SchemaResourceResourceSingleRoute: typeof SchemaResourceResourceSingleRoute
  SchemaResourceResourceTableRoute: typeof SchemaResourceResourceTableRoute
  SchemaResourceResourceIndexRoute: typeof SchemaResourceResourceIndexRoute
  SchemaResourceResourceResourceIdAuditRoute: typeof SchemaResourceResourceResourceIdAuditRoute
  SchemaResourceResourceResourceIdCommentRoute: typeof SchemaResourceResourceResourceIdCommentRoute
  SchemaResourceResourceResourceIdDetailRoute: typeof SchemaResourceResourceResourceIdDetailRoute
  SchemaResourceResourceResourceIdUpdateRoute: typeof SchemaResourceResourceResourceIdUpdateRoute
  SchemaResourceResourceCalendarCalendarIdRoute: typeof SchemaResourceResourceCalendarCalendarIdRoute
  SchemaResourceResourceGalleryGalleryIdRoute: typeof SchemaResourceResourceGalleryGalleryIdRoute
  SchemaResourceResourceKanbanKanbanIdRoute: typeof SchemaResourceResourceKanbanKanbanIdRoute
  SchemaResourceResourceListListIdRoute: typeof SchemaResourceResourceListListIdRoute
}

const SchemaResourceResourceRouteRouteChildren: SchemaResourceResourceRouteRouteChildren =
  {
    SchemaResourceResourceGridRoute: SchemaResourceResourceGridRoute,
    SchemaResourceResourceNewRoute: SchemaResourceResourceNewRoute,
    SchemaResourceResourceSingleRoute: SchemaResourceResourceSingleRoute,
    SchemaResourceResourceTableRoute: SchemaResourceResourceTableRoute,
    SchemaResourceResourceIndexRoute: SchemaResourceResourceIndexRoute,
    SchemaResourceResourceResourceIdAuditRoute:
      SchemaResourceResourceResourceIdAuditRoute,
    SchemaResourceResourceResourceIdCommentRoute:
      SchemaResourceResourceResourceIdCommentRoute,
    SchemaResourceResourceResourceIdDetailRoute:
      SchemaResourceResourceResourceIdDetailRoute,
    SchemaResourceResourceResourceIdUpdateRoute:
      SchemaResourceResourceResourceIdUpdateRoute,
    SchemaResourceResourceCalendarCalendarIdRoute:
      SchemaResourceResourceCalendarCalendarIdRoute,
    SchemaResourceResourceGalleryGalleryIdRoute:
      SchemaResourceResourceGalleryGalleryIdRoute,
    SchemaResourceResourceKanbanKanbanIdRoute:
      SchemaResourceResourceKanbanKanbanIdRoute,
    SchemaResourceResourceListListIdRoute:
      SchemaResourceResourceListListIdRoute,
  }

const SchemaResourceResourceRouteRouteWithChildren =
  SchemaResourceResourceRouteRoute._addFileChildren(
    SchemaResourceResourceRouteRouteChildren
  )

interface SchemaRouteRouteChildren {
  SchemaIndexRoute: typeof SchemaIndexRoute
  SchemaResourceResourceRouteRoute: typeof SchemaResourceResourceRouteRouteWithChildren
  SchemaChartIndexRoute: typeof SchemaChartIndexRoute
  SchemaDashboardIndexRoute: typeof SchemaDashboardIndexRoute
  SchemaReportIndexRoute: typeof SchemaReportIndexRoute
  SchemaTemplateIndexRoute: typeof SchemaTemplateIndexRoute
  SchemaReportReportIndexRoute: typeof SchemaReportReportIndexRoute
  SchemaSqlEditorSnippetIndexRoute: typeof SchemaSqlEditorSnippetIndexRoute
  SchemaTemplateTemplateIndexRoute: typeof SchemaTemplateTemplateIndexRoute
}

const SchemaRouteRouteChildren: SchemaRouteRouteChildren = {
  SchemaIndexRoute: SchemaIndexRoute,
  SchemaResourceResourceRouteRoute:
    SchemaResourceResourceRouteRouteWithChildren,
  SchemaChartIndexRoute: SchemaChartIndexRoute,
  SchemaDashboardIndexRoute: SchemaDashboardIndexRoute,
  SchemaReportIndexRoute: SchemaReportIndexRoute,
  SchemaTemplateIndexRoute: SchemaTemplateIndexRoute,
  SchemaReportReportIndexRoute: SchemaReportReportIndexRoute,
  SchemaSqlEditorSnippetIndexRoute: SchemaSqlEditorSnippetIndexRoute,
  SchemaTemplateTemplateIndexRoute: SchemaTemplateTemplateIndexRoute,
}

const SchemaRouteRouteWithChildren = SchemaRouteRoute._addFileChildren(
  SchemaRouteRouteChildren
)

interface AccountRouteRouteChildren {
  AccountIdentitiesRoute: typeof AccountIdentitiesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRolesPermissionsRoute: typeof AccountRolesPermissionsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIdentitiesRoute: AccountIdentitiesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRolesPermissionsRoute: AccountRolesPermissionsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren
)

interface AiChatRouteRouteChildren {
  AiChatIndexRoute: typeof AiChatIndexRoute
}

const AiChatRouteRouteChildren: AiChatRouteRouteChildren = {
  AiChatIndexRoute: AiChatIndexRoute,
}

const AiChatRouteRouteWithChildren = AiChatRouteRoute._addFileChildren(
  AiChatRouteRouteChildren
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren
)

interface CoreUsersUserIdRouteRouteChildren {
  CoreUsersUserIdDangerRoute: typeof CoreUsersUserIdDangerRoute
  CoreUsersUserIdEditRoute: typeof CoreUsersUserIdEditRoute
  CoreUsersUserIdSecurityRoute: typeof CoreUsersUserIdSecurityRoute
  CoreUsersUserIdIndexRoute: typeof CoreUsersUserIdIndexRoute
}

const CoreUsersUserIdRouteRouteChildren: CoreUsersUserIdRouteRouteChildren = {
  CoreUsersUserIdDangerRoute: CoreUsersUserIdDangerRoute,
  CoreUsersUserIdEditRoute: CoreUsersUserIdEditRoute,
  CoreUsersUserIdSecurityRoute: CoreUsersUserIdSecurityRoute,
  CoreUsersUserIdIndexRoute: CoreUsersUserIdIndexRoute,
}

const CoreUsersUserIdRouteRouteWithChildren =
  CoreUsersUserIdRouteRoute._addFileChildren(CoreUsersUserIdRouteRouteChildren)

interface CoreRouteRouteChildren {
  CoreIndexRoute: typeof CoreIndexRoute
  CoreUsersUserIdRouteRoute: typeof CoreUsersUserIdRouteRouteWithChildren
  CoreAudit_logsAuditLogIdRoute: typeof CoreAudit_logsAuditLogIdRoute
  CoreRole_permissionsNewRoute: typeof CoreRole_permissionsNewRoute
  CoreUser_rolesNewRoute: typeof CoreUser_rolesNewRoute
  CoreUsersInviteRoute: typeof CoreUsersInviteRoute
  CoreUsersNewRoute: typeof CoreUsersNewRoute
  CoreAudit_logsIndexRoute: typeof CoreAudit_logsIndexRoute
  CoreNotificationsIndexRoute: typeof CoreNotificationsIndexRoute
  CoreRole_permissionsIndexRoute: typeof CoreRole_permissionsIndexRoute
  CoreUser_rolesIndexRoute: typeof CoreUser_rolesIndexRoute
  CoreUsersIndexRoute: typeof CoreUsersIndexRoute
}

const CoreRouteRouteChildren: CoreRouteRouteChildren = {
  CoreIndexRoute: CoreIndexRoute,
  CoreUsersUserIdRouteRoute: CoreUsersUserIdRouteRouteWithChildren,
  CoreAudit_logsAuditLogIdRoute: CoreAudit_logsAuditLogIdRoute,
  CoreRole_permissionsNewRoute: CoreRole_permissionsNewRoute,
  CoreUser_rolesNewRoute: CoreUser_rolesNewRoute,
  CoreUsersInviteRoute: CoreUsersInviteRoute,
  CoreUsersNewRoute: CoreUsersNewRoute,
  CoreAudit_logsIndexRoute: CoreAudit_logsIndexRoute,
  CoreNotificationsIndexRoute: CoreNotificationsIndexRoute,
  CoreRole_permissionsIndexRoute: CoreRole_permissionsIndexRoute,
  CoreUser_rolesIndexRoute: CoreUser_rolesIndexRoute,
  CoreUsersIndexRoute: CoreUsersIndexRoute,
}

const CoreRouteRouteWithChildren = CoreRouteRoute._addFileChildren(
  CoreRouteRouteChildren
)

interface StorageBucketIdRouteRouteChildren {
  StorageBucketIdSplatRoute: typeof StorageBucketIdSplatRoute
  StorageBucketIdIndexRoute: typeof StorageBucketIdIndexRoute
}

const StorageBucketIdRouteRouteChildren: StorageBucketIdRouteRouteChildren = {
  StorageBucketIdSplatRoute: StorageBucketIdSplatRoute,
  StorageBucketIdIndexRoute: StorageBucketIdIndexRoute,
}

const StorageBucketIdRouteRouteWithChildren =
  StorageBucketIdRouteRoute._addFileChildren(StorageBucketIdRouteRouteChildren)

interface StorageRouteRouteChildren {
  StorageBucketIdRouteRoute: typeof StorageBucketIdRouteRouteWithChildren
  StorageIndexRoute: typeof StorageIndexRoute
}

const StorageRouteRouteChildren: StorageRouteRouteChildren = {
  StorageBucketIdRouteRoute: StorageBucketIdRouteRouteWithChildren,
  StorageIndexRoute: StorageIndexRoute,
}

const StorageRouteRouteWithChildren = StorageRouteRoute._addFileChildren(
  StorageRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemaRouteRoute: SchemaRouteRouteWithChildren,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AiChatRouteRoute: AiChatRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CoreRouteRoute: CoreRouteRouteWithChildren,
  StorageRouteRoute: StorageRouteRouteWithChildren,
  InitRoute: InitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
