/*
 * -------------------------------------------------------
 * Section: Configs
 * Key-value configuration store for app-wide settings.
 * -------------------------------------------------------
 */
create table if not exists supasheet.configs (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb,
  description text,
  is_public boolean not null default false
);

comment on table supasheet.configs is '{
  "label": "Configs",
  "icon": "SettingsIcon"
}';

create index idx_configs_key on supasheet.configs (key);

create index idx_configs_is_public on supasheet.configs (is_public)
where
  is_public = true;

revoke all on supasheet.configs
from
  anon,
  authenticated,
  public,
  service_role;

grant
select
  on table supasheet.configs to anon,
  authenticated;

alter table supasheet.configs enable row level security;

create policy configs_select_anon on supasheet.configs for
select
  to anon using (is_public);

create policy configs_select_authenticated on supasheet.configs for
select
  to authenticated using (true);
